const ADMIN_API = "https://arash-api.arash-pashazadeh1.workers.dev";
const SECRET_KEY = "arash_admin_session_secret";
let adminSecret = sessionStorage.getItem(SECRET_KEY) || "";
let caches = { publications: [], projects: [], conferences: [] };

const $ = (id) => document.getElementById(id);
function authHeaders(json=true){const h={Authorization:`Bearer ${adminSecret}`};if(json)h["Content-Type"]="application/json";return h;}
function setMessage(id,text,type=""){const el=$(id);if(!el)return;el.textContent=text;el.className=`form-message ${type}`.trim();}
async function adminFetch(path, options={}){const res=await fetch(`${ADMIN_API}${path}`,{...options,headers:{...authHeaders(options.body!==undefined),...(options.headers||{})}});let data=null;try{data=await res.json();}catch{}if(!res.ok)throw new Error(data?.error||`HTTP ${res.status}`);return data;}
async function publicFetch(path){const res=await fetch(`${ADMIN_API}${path}?t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json();}

function showDashboard(){ $("admin-login").hidden=true; $("admin-dashboard").hidden=false; refreshAll(); }
function showLogin(){ $("admin-login").hidden=false; $("admin-dashboard").hidden=true; }
async function verifySecret(secret){adminSecret=secret;await adminFetch("/admin/ping",{method:"GET"});sessionStorage.setItem(SECRET_KEY,secret);showDashboard();}
$("admin-login-form")?.addEventListener("submit",async(e)=>{e.preventDefault();setMessage("admin-login-message","Checking…");try{await verifySecret($("admin-secret").value);setMessage("admin-login-message","");}catch(err){adminSecret="";sessionStorage.removeItem(SECRET_KEY);setMessage("admin-login-message",err.message,"error");}});
$("admin-logout")?.addEventListener("click",()=>{adminSecret="";sessionStorage.removeItem(SECRET_KEY);showLogin();});
if(adminSecret){verifySecret(adminSecret).catch(()=>{adminSecret="";sessionStorage.removeItem(SECRET_KEY);showLogin();});}else showLogin();

// Tabs
document.querySelectorAll(".admin-tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(b=>b.classList.toggle("active",b===btn));document.querySelectorAll(".admin-panel").forEach(p=>p.classList.toggle("active",p.dataset.panel===btn.dataset.tab));}));

document.querySelectorAll("[data-refresh]").forEach(btn=>btn.addEventListener("click",()=>refreshResource(btn.dataset.refresh)));

function adminItem(item, resource, subtitle){const row=document.createElement("div");row.className="admin-item";const info=document.createElement("div");const h=document.createElement("h4");h.textContent=item.title;const p=document.createElement("p");p.textContent=subtitle;info.append(h,p);const actions=document.createElement("div");actions.className="admin-item-actions";const edit=document.createElement("button");edit.type="button";edit.textContent="Edit";edit.addEventListener("click",()=>editItem(resource,item));const del=document.createElement("button");del.type="button";del.className="danger";del.textContent="Delete";del.addEventListener("click",()=>deleteItem(resource,item));actions.append(edit,del);row.append(info,actions);return row;}
async function refreshResource(resource){const map={publications:["/publications","admin-publications"],projects:["/projects","admin-projects"],conferences:["/conferences","admin-conferences"]};const [path,id]=map[resource];const el=$(id);el.innerHTML='<div class="data-loading">Loading…</div>';try{const rows=await publicFetch(path);caches[resource]=rows;el.innerHTML="";rows.forEach(item=>{let sub="";if(resource==="publications")sub=[item.year,item.journal,item.status,item.featured?"Featured":""].filter(Boolean).join(" · ");if(resource==="projects")sub=[item.category,item.kind,item.status,item.featured?"Featured":""].filter(Boolean).join(" · ");if(resource==="conferences")sub=[item.year,item.event,item.type,item.featured?"Featured":""].filter(Boolean).join(" · ");el.appendChild(adminItem(item,resource,sub));});if(!rows.length)el.innerHTML='<div class="data-loading">No entries yet.</div>';}catch(err){el.innerHTML=`<div class="posts-error">${err.message}</div>`;}}
async function refreshAll(){await Promise.all([refreshResource("publications"),refreshResource("projects"),refreshResource("conferences")]);}

async function deleteItem(resource,item){if(!confirm(`Delete “${item.title}”?`))return;try{await adminFetch(`/admin/${resource}/${item.id}`,{method:"DELETE"});await refreshResource(resource);}catch(err){alert(err.message);}}
function editItem(resource,item){document.querySelector(`.admin-tab[data-tab="${resource.slice(0,-1)}"]`)?.click();if(resource==="publications")fillPublication(item);if(resource==="projects")fillProject(item);if(resource==="conferences")fillConference(item);window.scrollTo({top:document.querySelector(`.admin-panel.active`).offsetTop-90,behavior:"smooth"});}

function resetPublication(){$("publication-form").reset();$("publication-id").value="";$("publication-form-title").textContent="Add publication";setMessage("publication-message","");}
function fillPublication(x){$("publication-id").value=x.id;$("pub-doi").value=x.doi||"";$("pub-title").value=x.title||"";$("pub-authors").value=x.authors||"";$("pub-journal").value=x.journal||"";$("pub-year").value=x.year||"";$("pub-status").value=x.status||"Published";$("pub-url").value=x.url||"";$("pub-pdf").value=x.pdf_url||"";$("pub-abstract").value=x.abstract||"";$("pub-featured").checked=Boolean(x.featured);$("publication-form-title").textContent="Edit publication";}
$("publication-reset")?.addEventListener("click",resetPublication);
$("doi-lookup")?.addEventListener("click",async()=>{const doi=$("pub-doi").value.trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,"");if(!doi){setMessage("publication-message","Enter a DOI first.","error");return;}setMessage("publication-message","Looking up DOI…");try{const res=await fetch(`${ADMIN_API}/doi?doi=${encodeURIComponent(doi)}`);const x=await res.json();if(!res.ok)throw new Error(x.error||"DOI lookup failed");$("pub-doi").value=x.doi||doi;$("pub-title").value=x.title||"";$("pub-authors").value=x.authors||"";$("pub-journal").value=x.journal||"";$("pub-year").value=x.year||"";$("pub-url").value=x.url||`https://doi.org/${doi}`;setMessage("publication-message","DOI data loaded. Review it, then Save.","success");}catch(err){setMessage("publication-message",err.message,"error");}});
$("publication-form")?.addEventListener("submit",async(e)=>{e.preventDefault();const id=$("publication-id").value;const body={doi:$("pub-doi").value.trim(),title:$("pub-title").value.trim(),authors:$("pub-authors").value.trim(),journal:$("pub-journal").value.trim(),year:Number($("pub-year").value)||null,status:$("pub-status").value,url:$("pub-url").value.trim(),pdf_url:$("pub-pdf").value.trim(),abstract:$("pub-abstract").value.trim(),featured:$("pub-featured").checked};setMessage("publication-message","Saving…");try{await adminFetch(id?`/admin/publications/${id}`:"/admin/publications",{method:id?"PUT":"POST",body:JSON.stringify(body)});setMessage("publication-message","Saved. The public site is updated automatically.","success");resetPublication();await refreshResource("publications");}catch(err){setMessage("publication-message",err.message,"error");}});

function resetProject(){$("project-form").reset();$("project-id").value="";$("project-form-title").textContent="Add project";$("project-image-preview").hidden=true;setMessage("project-message","");}
function fillProject(x){$("project-id").value=x.id;$("proj-title").value=x.title||"";$("proj-category").value=x.category||"";$("proj-kind").value=x.kind||"research";$("proj-status").value=x.status||"";$("proj-featured").checked=Boolean(x.featured);$("proj-start-year").value=x.start_year||"";$("proj-end-year").value=x.end_year||"";$("proj-summary").value=x.summary||"";$("proj-description").value=x.description||"";$("proj-methods").value=x.methods||"";$("proj-image").value=x.image_url||"";$("proj-url").value=x.project_url||"";$("project-form-title").textContent="Edit project";updateImagePreview();}
function updateImagePreview(){const url=$("proj-image")?.value.trim();const box=$("project-image-preview");if(!box)return;if(url){box.hidden=false;box.querySelector("img").src=url;}else box.hidden=true;}
$("proj-image")?.addEventListener("input",updateImagePreview);$("project-reset")?.addEventListener("click",resetProject);
$("project-form")?.addEventListener("submit",async(e)=>{e.preventDefault();const id=$("project-id").value;const body={title:$("proj-title").value.trim(),category:$("proj-category").value.trim(),kind:$("proj-kind").value,status:$("proj-status").value.trim(),featured:$("proj-featured").checked,start_year:Number($("proj-start-year").value)||null,end_year:Number($("proj-end-year").value)||null,summary:$("proj-summary").value.trim(),description:$("proj-description").value.trim(),methods:$("proj-methods").value.trim(),image_url:$("proj-image").value.trim(),project_url:$("proj-url").value.trim()};setMessage("project-message","Saving…");try{await adminFetch(id?`/admin/projects/${id}`:"/admin/projects",{method:id?"PUT":"POST",body:JSON.stringify(body)});setMessage("project-message","Saved. The public site is updated automatically.","success");resetProject();await refreshResource("projects");}catch(err){setMessage("project-message",err.message,"error");}});

function resetConference(){$("conference-form").reset();$("conference-id").value="";$("conference-form-title").textContent="Add conference";setMessage("conference-message","");}
function fillConference(x){$("conference-id").value=x.id;$("conf-title").value=x.title||"";$("conf-event").value=x.event||"";$("conf-type").value=x.type||"";$("conf-year").value=x.year||"";$("conf-location").value=x.location||"";$("conf-description").value=x.description||"";$("conf-url").value=x.url||"";$("conf-featured").checked=Boolean(x.featured);$("conference-form-title").textContent="Edit conference";}
$("conference-reset")?.addEventListener("click",resetConference);
$("conference-form")?.addEventListener("submit",async(e)=>{e.preventDefault();const id=$("conference-id").value;const body={title:$("conf-title").value.trim(),event:$("conf-event").value.trim(),type:$("conf-type").value.trim(),year:Number($("conf-year").value)||null,location:$("conf-location").value.trim(),description:$("conf-description").value.trim(),url:$("conf-url").value.trim(),featured:$("conf-featured").checked};setMessage("conference-message","Saving…");try{await adminFetch(id?`/admin/conferences/${id}`:"/admin/conferences",{method:id?"PUT":"POST",body:JSON.stringify(body)});setMessage("conference-message","Saved. The public site is updated automatically.","success");resetConference();await refreshResource("conferences");}catch(err){setMessage("conference-message",err.message,"error");}});
